# CLAUDE.md — {{PROJECT_NAME}}

> Auto-generated by `/init` on {{INIT_DATE}}.
> Project-specific config for Claude Code.
> Full rules: see `AGENTS.md`.

---

## Stack

**{{STACK}}**

---

## Commands

| Action     | Command                 |
|------------|-------------------------|
| Dev server | `{{DEV_COMMAND}}`       |
| Tests      | `{{TEST_COMMAND}}`      |
| Lint       | `{{LINT_COMMAND}}`      |
| Build      | `{{BUILD_COMMAND}}`     |

---

## Architecture

{{ARCHITECTURE_SUMMARY}}

Key files:
- `{{KEY_FILE_1}}` — {{KEY_FILE_1_DESC}}
- `{{KEY_FILE_2}}` — {{KEY_FILE_2_DESC}}
- `{{KEY_FILE_3}}` — {{KEY_FILE_3_DESC}}

---

## Project-Specific Hard Rules

- {{PROJECT_RULE_1}}
- {{PROJECT_RULE_2}}
- Do not start coding without an approved plan (`/plan` first)
- Do not touch files outside the current task scope

---

## Active Skills

Skills relevant to this project (load on demand):
{{ACTIVE_SKILLS_LIST}}

Full catalog: `skills/SKILLS_INDEX.md`

---

## Active MCP Servers

Configured in `mcp/active-servers.json`:
{{ACTIVE_MCP_LIST}}

---

## Response Language

{{LANGUAGE}}

---

## Full Config

See `AGENTS.md` for complete rules, workflow, and role definitions.
See `PROJECT_CONSTITUTION.md` for project scope and architecture.
